sboms:

  categories:

    - label: Products
      options:
        - label: Red Hat Enterprise Linux 7
          terms:
            - '"pkg:oci/redhat/ubi7"'

    - label: Type
      options:
        - label: Container
          terms:
            - 'type:oci'

    - label: Suppliers
      options:
        - label: Red Hat
          terms:
            - 'supplier:"Organization: Red Hat"'

advisories:
